[book]
authors = ["Aalekh Patel <aalekh.gwpeck.7998@icloud.com>"]
description = "A (WIP) guide to this implementation of the Tiger compiler."
language = "en"
multilingual = false
src = "book-src"
title = "tigers"

[rust]
edition = "2018"

[build]
build-dir = "docs"
create-missing = false

[output.html]
additional-css = ["custom.css"]

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 50
